### ISSUE TITLE
ES-Modulformat

### ISSUE THREAD

**Issue by L3P3** [LFF5644/frameBufferTest#2]
Statt require und module.exports (veraltet) solltest du import und export nehmen...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#exporting_module_features

**Comment by LFF5644** [comment]
habe überlegt ich bleibe beim alten da ich auf dem gerät auf dem ich derzeit programmiere nur nodejs 8 und npm 3 deswegen denke ich erstmal nicht über sowas nach

aber sehr aufmerksam
